name: 'medicine '
favicon: null
layout_spectrum: 0.10734244505874813
typography_spectrum: 0.1836490761488676
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#080808'
    - '#90b6dd'
    - '#625d59'
    - '#e8dfe2'
    - '#c68359'
  brandStrength: 0.050196272088214755
  lightness: 0
  saturation: 0.08152338257059455
  rhythmicContrast: 0.9190209982916713
purpose: []
